### ISSUE TITLE
The evidence and highlighted text is not updated if the query is repeated by only changing the source of information. 

### ISSUE THREAD

**Issue by cbadenes** [drugs4covid/web#29]

**Comment by Vitoriox** [comment]
I will need the params used in the search to make some test
I cant reproduce this issue by myself

**Comment by cbadenes** [comment]
question: What medication is used to treat schizophrenia?
max answers: 5

first execution: d4c (true), dbpedia (false), wikidata(false)
second execution: d4c (false), dbpedia (true), wikidata (false)
