### ISSUE TITLE
d4c.linkeddata.es/services/qa return 404 Not Found

### ISSUE THREAD

**Issue by cbadenes** [drugs4covid/web#32]
Is there static content for this resource? That URL is empty, but the resource is reached from the web

**Comment by Vitoriox** [comment]
The website as it is, is a  single page client side app, so it requires some server configuration to enable the history mode and prevent the 404
https://v3.router.vuejs.org/guide/essentials/history-mode.html

**Comment by Vitoriox** [comment]
Changes were made in the nginx config file, reboot form a sudo user is required

**Comment by Vitoriox** [comment]
Duplicated with Issue #9
