### ISSUE TITLE
Missing text labels in https://drugs4covid.oeg.fi.upm.es/corpus/text-search

### ISSUE THREAD

**Issue by cbadenes** [drugs4covid/web#41]
textSearch.title: Keyword-guided Resource Finder
textSearch.subtitle: Type one or more keywords and select the resource to retrieve: text, medicine or disease.
textSearch.placeholder: Remdesivir
textSearch.maxResults: Max Results (1 by default)
textSearch.subheader: Resource
textSearch.diseases: Diseases ( True by default)
textSearch.drugs: Drugs (True by default)
textSearch.Texts: Texts (True by default)

Sorry, but these options are not clear for me: 
textSearch.subheader:
textSearch.drugsFilter:
textSearch.diseasesFilter:

**Comment by Vitoriox** [comment]
The last ones correspond to the filter labels, like atc and mesh level filters
